#:schema https://raw.githubusercontent.com/cloudflare/wrangler/main/packages/wrangler/config-schema.json
name = "stage-onrivi-app"
compatibility_date = "2024-03-08"

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "onrivi_db"
database_id = "7ec7a183-0e56-477f-8f91-3f7a6921ed48"